//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolRegistrationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public System.DateTime dob { get; set; }
        public int age { get; set; }
        public int branch_id { get; set; }
        public int classid { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Processed_Application Processed_Application { get; set; }
    }
}
