//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolRegistrationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public string Category { get; set; }
        public string lstApplications { get; set; }
        public int TotalByCategory { get; set; }
        public int TotalNoOfApplications { get; set; }
    }
}
