//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolRegistrationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int branch_id { get; set; }
        public int classid { get; set; }
        public int seats { get; set; }
    }
}
